GET http://localhost:3000/api/hello

###

GET http://localhost:3000/api/products

###

GET http://localhost:3000/api/products/3

###

GET http://localhost:3000/api/users/1/cart

###

POST http://localhost:3000/api/users/1/cart
Content-Type: application/json

{
    "productId": "10"
}

###

GET http://localhost:3000/api/users/67802b1cef3f0c3b332d79a6

###


DELETE http://localhost:3000/api/users/1/cart
Content-Type: application/json

{
    "productId": "10"
}

###

POST http://localhost:3000/api/users/create
Content-Type: application/json 

{
    "username": "kobrius",
    "password": "aaa" 
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json 

{
    "username": "kobrius",
    "password": "aaaa" 
}